[workspace]
members = [
    "crates/unicode-pdf",
    "crates/unicode-pdf-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.3"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"
keywords = ["pdf", "unicode", "text", "typography", "harfrust"]
categories = ["text-processing", "encoding"]

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
