[package]
name = "unicode-pdf-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Development CLI for unicode-pdf"
publish = false

[features]
default = ["harfrust", "unicode-bidi"]
harfrust = ["unicode-pdf/harfrust"]
unicode-bidi = ["unicode-pdf/unicode-bidi"]
system-harfbuzz = ["unicode-pdf/system-harfbuzz"]
system-fribidi = ["unicode-pdf/system-fribidi"]

[dependencies]
unicode-pdf = { path = "../unicode-pdf", version = "0.1.0-alpha.3", default-features = false }

[lints]
workspace = true
